// Generated by LiveScript 1.2.0
(function(){
  window.l = function(){
    return console.log.apply(console, arguments);
  };
  requirejs.config({
    paths: {
      'text': '../lib/require/text',
      'durandal': '../lib/durandal/js',
      'plugins': '../lib/durandal/js/plugins',
      'transitions': '../lib/durandal/js/transitions',
      'knockout': '../lib/knockout/knockout-3.1.0',
      'knockout-punches': '../lib/knockout/knockout.punches.min',
      'bootstrap': '../lib/avant/js/bootstrap.min',
      'jquery': '../lib/avant/js/jquery-1.10.2.min'
    },
    shim: {
      'bootstrap': {
        deps: ['jquery'],
        exports: 'jQuery'
      }
    }
  });
  define(function(require){
    var system, app, viewLocator, ko;
    system = require('durandal/system');
    app = require('durandal/app');
    viewLocator = require('durandal/viewLocator');
    system.debug(true);
    ko = require('knockout');
    require('knockout-punches');
    ko.punches.interpolationMarkup.enable();
    ko.punches.attributeInterpolationMarkup.enable();
    app.title = 'ngANU';
    app.configurePlugins({
      router: true,
      dialog: true,
      widget: true,
      observable: true
    });
    return app.start().then(function(){
      viewLocator.useConvention();
      return app.setRoot('shell', void 8, 'app-host');
    });
  });
}).call(this);
