// Generated by LiveScript 1.2.0
(function(){
  define(function(require){
    var context;
    return context = {
      router: require('plugins/router'),
      activate: function(){
        context.router.map({
          route: '',
          title: 'Server Status',
          moduleId: 'service/control',
          nav: true
        }, {
          route: 'test',
          title: 'Meong',
          moduleId: 'test/meong',
          nav: true
        });
        return context.router.activate();
      }
    };
  });
}).call(this);
